config/routes.rb
Zagogulin::Application.routes.draw do
  
  resources :categories, shallow: true do
  	collection do
  	  post 'sort'
  	end
    resources :goods, except: :index
  end

  root :to => 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent_id, :slug, :cat_order
  has_many :goods

  extend FriendlyId
  friendly_id :name, use: :slugged

  include ActsAsTree
  acts_as_tree :order => 'cat_order'

end

app/models/good.rb
class Good < ActiveRecord::Base
  attr_accessible :category_id, :name, :slug, :image, :description

  belongs_to :category
  has_attached_file :image, styles: { preview: '75x75', normal: '800x600' }, default_url: "/images/:style/missing.gif"

  extend FriendlyId
  friendly_id :name, use: :slugged

  def self.uncategorized
  	Good.all - Category.all.map {|c| c.goods }.flatten 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.roots
    @uncategorizedGoods = Good.uncategorized
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def sort
     i = 0
     params[:category_ids].each do |id, parent_id|
       @category = Category.find(id.to_i)
       parent_id = (parent_id == 'null' ? nil : parent_id.to_i)
       @category.parent_id = parent_id
       @category.cat_order = i+= 1
       @category.save
    end
    render json: { ok: true } 
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController

  # GET /goods/1
  # GET /goods/1.json
  def show
    @good = Good.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @good }
    end
  end

  # GET /goods/new
  # GET /goods/new.json
  def new
    @good = Good.new
    @good.category = Category.find_by_slug params[:category_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @good }
    end
  end

  # GET /goods/1/edit
  def edit
    @good = Good.find(params[:id])
    @good.category_id = params[:category_id]
  end

  # POST /goods
  # POST /goods.json
  def create
    @good = Good.new(params[:good])
    @good.category = Category.find_by_slug params[:category_id]

    respond_to do |format|
      if @good.save
        format.html { redirect_to @good.category, notice: 'Good was successfully created.' }
        format.json { render json: @good, status: :created, location: @good }
      else
        format.html { render action: "new" }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /goods/1
  # PUT /goods/1.json
  def update
    @good = Good.find(params[:id])

    respond_to do |format|
      if @good.update_attributes(params[:good])
        format.html { redirect_to @good.category, notice: 'Good was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goods/1
  # DELETE /goods/1.json
  def destroy
    @good = Good.find_by_slug(params[:id])
    @good.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">

    <%= f.label :name %>
    <%= f.text_field :name %>
    <% if params[:parent_id] %>
      <%= f.hidden_field :parent_id, value: params[:parent_id] %>
    <% end %>

    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_goods.html.erb
<% goods.each do |good| %>
  <div style="background:<%= cycle('#C6EE89', '#CCB8F5' )%>; width: 400px; margin: 10px 0;" >
    <i>Item:</i> <%= link_to good.name, good %> | 
    <%= link_to 'Edit', edit_good_path(good) %> |
    <%= link_to 'Destroy', good, method: :delete, data: { confirm: 'Are you sure?' } %>
      <div style='width: 500px;'>
        <%= image_tag good.image.url(:preview) %>
        <%= good.description %>
      </div>
  </div>
<% end %>

app/views/categories/_subcategories.html.erb
<ul id = "<%= 'categories-root' if defined? first %>" >
  <% categories.each do |category| %>
      <li id = "category_<%= category.id %>" style='border: 1px solid;margin:10px 0;' class='category'>
        <div>
          <i>Category:</i> <%= link_to category.name, category %>
        | <%= link_to 'Edit', edit_category_path(category) %>
        <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'Create child category', new_category_path( parent_id: category.id ) %>
        <%= render partial: 'goods', locals: { goods: category.goods } %>
         <%=  link_to 'Create a good here', new_category_good_path(category, category_orig_id: category.id) %>
        </div>
        <%= render partial: 'subcategories', locals: { categories: category.children, first: false } if category.children.present? %>
      </li>
  <% end %>
</ul>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/delete.html.erb
<h1>Categories#delete</h1>
<p>Find me in app/views/categories/delete.html.erb</p>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% if @categories.present? %>
  <h1>All Categories</h1>
<% end %>

<p id='notice'><%= notice %></p>
<%= render partial: 'subcategories', locals: { categories: @categories, first: true } %>
<h1>
  <%= link_to 'Create root category', new_category_path %>
</h1>
<br />
<% if @uncategorizedGoods.present? %>
  <h1>Uncategorized items:</h1>
  <%= render partial: 'goods', locals: { goods: @uncategorizedGoods } %>
<% end %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<h2> Content of category <%= @category.name %> </h2>
<%= render partial: 'subcategories', locals: { categories: [@category], first: true } %>
<% if @category.parent %>
  <%= link_to 'Back to parent category', category_path(@category.parent) %> |
<% end %>
<%= link_to 'Back to all categories', categories_path %>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/goods/_form.html.erb
<%= form_for [@good.category, @good], :html => { :multipart => true }  do |f| %>
  <% if @good.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@good.errors.count, "error") %> prohibited this good from being saved:</h2>

      <ul>
      <% @good.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">

    <%= f.label :name %>
    <br />
    <%= f.text_field :name %>
    <br />
    <%= f.label :description %>
    <br />
    <%= f.text_area :description, :size => '50x10' %>
    <br />
    <%= f.label :image %>
    <br />
    <%= f.file_field :image %>
    <br />
    <br />

    <%= f.submit %>
  </div>
<% end %>

app/views/goods/edit.html.erb
<h1>Edit good <%= @good.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @good %>

app/views/goods/new.html.erb
<h1>New good</h1>

<%= render 'form' %>

<%= link_to 'Back to category', @good.category %>
<br>
<%= link_to 'Back to All categories', categories_path %>

app/views/goods/show.html.erb
<h1>Show good <%= @good.name %></h1>
<p id="notice"><%= notice %></p>
 <div style='width: 500px;'>
  <%= image_tag @good.image.url(:normal) %>
  <%= @good.description %>
</div>
<%= link_to 'Edit', edit_good_path(@good) %> |
<%= link_to 'Back', @good.category %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zagogulin</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>